version: '5'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - /opt/mongo_data:/var/lib/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      shared-net:
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      shared-net:
  missenger:
    container_name: missenger
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - mongo
    depends_on:
      - mongo
    restart: on-failure
    ports:
      - 8088:8088
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=missenger
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - SERVER_PORT=8088
    networks:
      shared-net:
volumes:
  mongo: {}
networks:
  shared-net:
