spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:missenger}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:root}
      authentication-database: admin
server:
  port: ${SERVER_PORT:8088}
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: webrtc
    key-store-type: PKCS12
    key-alias: webrtc