spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: missenger

server:
  port: 8088
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: webrtc
    key-store-type: PKCS12
    key-alias: webrtc