spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:missenger}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT:8088}
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: webrtc
    key-store-type: PKCS12
    key-alias: webrtc